languageCode = "en"
languageName = "English"
weight = 5
title = "WZ Chen"

[params]
displayName = "English"
isoCode = "en"
rtl = false
dateFormat = "2006-01-02"
description = ""

[params.author]
name = "WZ Chen"
email = "110356047@g.nccu.edu.tw"
image = "img/seal.jpg"
headline = "你今天寫 code 了嗎"
bio = "你今天寫 code 了嗎"
links = [
  { linkedin = "https://www.linkedin.com/in/weizhe-chen-6b28a5131/" },
  { github = "https://github.com/weiz-98" },
]
